### PR TITLE
Support deb ipk and other fixes

### PR DESCRIPTION
**Pull request by robertlinux**
Hi maintainer,

This PULL contains the one that I had submiited 7 days ago, you can ignore that one (Pkgdiff faster #9) .There are 7 commits in this PULL:
* The first 2 are used for making pkg-diff.sh run master (75% faster when the pkgs are indentical)
* The 3, 4, 5 are fixes for pkg-diff.sh
* The 6 and 7 are used for supporting deb and ipk, they should be squashed into 1 commit, but are made by different authors, so I leave them as two.

Please feel free to give your comments.

### CODE REVIEW

**Comment by olafhering** [comment]
Regarding commit "functions.sh: remove space at head", I think the issue is that space after each $QF, and the missing newline after DISTURL.

**Comment by olafhering** [comment]
Regarding commit " functions.sh: run rpm once to make it faster", there are a few unrelated changes. A few local variables in one function are accessed in another function. I think we should aim for local variables and remove globals as needed.

**Comment by robertlinux** [comment]
Hi Olaf,

Thanks for the reply.
 * For "functions.sh: remove space at head", yes, you are right, I will update QF and DISTURL, then drop this patch.

* For " functions.sh: run rpm once to make it faster":
  - The unrelated changes: I think that you mean the vars file1 -> file_old, file2 -> file_new, I will change them back.
  -  The local vars: spec_old and spec_new are accessed by comp_file(), I will fix it.

Please see the updated one (PULL #11 )

**Comment by robertlinux** [comment]
Hi Olaf,

I'm sorry, I just found that I can update PULL #10 directly rather then send a new PULL, so I closed PULL #11, and updated the existed PULL #10.

* Changes of V2:
  - Drop "functions.sh: remove space at head", fix QF and DISTURL instead.
  - functions.sh: run rpm once to make it faster
    a) Drop unrelated changes.
    b) Fix local vars accessed by other functions.

**Comment by robertlinux** [comment]
Hi Olaf,
@olafhering , do you have any comments, please ?

**Comment by olafhering** [comment]
Regarding adjust_controlfile(), is there no 'sed -i' available?

**Comment by robertlinux** [comment]
Hi Olaf,
@olafhering , thanks for the reply and merge, I think that you meant:

+function adjust_controlfile() {
+    cat $1/control | sed '/^Version: /d' > $1/control.fixed
+    mv $1/control.fixed $1/control
+    cat $2/control | sed '/^Version: /d' > $2/control.fixed
+    mv $2/control.fixed $2/control
+}

That was from another author, and I've updated it in another commit:
 function adjust_controlfile() {
-    cat $1/control | sed '/^Version: /d' > $1/control.fixed
+    version_release_old="`sed -ne 's/^Version: \(.*\)/\1/p' $1/control`"
+    name_ver_rel_old="`sed -n -e 's/^Package: \(.*\)/\1/p' $1/control`-`sed -n -e 's/^Version: \(.*\)/\1/p' $1/control`"
+    version_release_new="`sed -ne 's/^Version: \(.*\)/\1/p' $2/control`"
+    name_ver_rel_new="`sed -n -e 's/^Package: \(.*\)/\1/p' $2/control`-`sed -n -e 's/^Version: \(.*\)/\1/p' $2/control`"
+    set_regex
+    cat $1/control | trim_release_old > $1/control.fixed
     mv $1/control.fixed $1/control
-    cat $2/control | sed '/^Version: /d' > $2/control.fixed
+    cat $2/control | trim_release_new > $2/control.fixed
     mv $2/control.fixed $2/control
 }

**Pull request merged**
